### ISSUE TITLE
Failed to resolve: play-services-basement

### ISSUE THREAD

**Issue by TStevens13** [adafruit/Bluefruit_LE_Connect_Android_V2#1]
I keep getting this error when building the app.
It then gives a link to 'app\build.gradle'

**Comment by antonio-openroad** [comment]
Make sure that you are using the latest version of Android Studio (3.4.1) and clean the project and rebuild it.
More info in stackoverflow: https://stackoverflow.com/questions/52948514/android-gradle-failed-to-resolve-play-services-basement
