### ISSUE TITLE
Upload custom firmware fails with no Internet connection

### ISSUE THREAD

**Issue by thelackey3326** [adafruit/Bluefruit_LE_Connect_Android_V2#12]
I have a the hex and init files saved on my Android device. Uploading them should not require an Internet connection.

Repro:
1) Download the hex and init files directly, or otherwise copy them to your device
2) Connect to your Bluefruit using the app
3) Select Updates
4) Select Use Custom Firmware at the bottom
5) Choose the hex file
6) Choose the init file
7) Start Update

Result:
An error message pops up "Error downloading files. Check your internet connection and try again."

Expected:
Use the files supplied in steps 5 & 6.

**Comment by antonio-openroad** [comment]
Thanks for reporting the problem. 
You are right, there is an internet connection check that is not needed for local files.
