### ISSUE TITLE
Tabs dont display on android 11?

### ISSUE THREAD

**Issue by bm16ton** [adafruit/Bluefruit_LE_Connect_Android_V2#22]
Hello, great app i love it! Works great on my android 7 phone, but on android 11 none of the tabs IE "uart" show up. Unfortunatly i dont have access to any other newer android devices so im not sure if its justmy device type thing orif android made breaking changes along the way so i tthought i ask and see if anyone else has similiar issue. Thank you

**Comment by antonio-openroad** [comment]
Hi,
Could you provide more info about the peripheral that you are connecting to, and the Android Phone model?

I just tested the app and the UART sections are displayed when connecting to a UART enabled peripheral (Adafruit Bluefruit LE Friend)

Tested on the following devices:
- Samsung Galaxy A40, Android 11
- Pixel 3a, Android 12
- Samsung GalaxyTab A7 Lite, Android 12
- Pixel 6, Android 13

Screenshot with the sections displayed:
![Screenshot_20221206_163228](https://user-images.githubusercontent.com/3625420/205954808-49d0fcef-ca7c-43cb-b11f-08ee3d157e16.png)

**Comment by bm16ton** [comment]
Thank you so much for responding! I know you must be busy. Its a oneplus 7 pro, the device is seeed xiao nrf52840. I tried all the uart examples from adafruit,nrf etc. But i now know its my phone and not the app, thats the info i needed to move forward. Thank you again kind sir
