### ISSUE TITLE
fix or remove reference to "Export" data from console

### ISSUE THREAD

**Issue by ladyada** [adafruit/Bluefruit_LE_Connect_Android_V2#4]
hiya @antonio-openroad if we dont have this functionality, remove the text
https://forums.adafruit.com/viewtopic.php?f=8&t=143749&p=712213

**Comment by antonio-openroad** [comment]
Hi. It is my fault, I forgot to port the export feature from iOS.
I will submit a new version removing the text.

**Comment by ladyada** [comment]
thanks :)
